"""
Django settings for relationship_app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+q%bt#=l#++il=)zq3ps4^+b##+w&t#gs+b$+@6z=y=n$c$8%4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'relationship_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'relationship_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

ADMIN_ENABLED = TRUE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from django.contrib.auth import get_user_model
User = get_user_model()

# settings.py (production-minded)
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# load from env: use a real env loader in production (dotenv, os.environ, or secret manager)
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Make sure DEBUG is False in production
if DEBUG:
    # Only allow DEBUG in development
    print("WARNING: DEBUG is True. Do not use in production!")

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')  # must be set in prod, never committed

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'example.com').split(',')

# === Security-related cookie & header settings ===
CSRF_COOKIE_SECURE = True              # only send CSRF cookie over HTTPS
SESSION_COOKIE_SECURE = True           # only send session cookie over HTTPS
CSRF_COOKIE_HTTPONLY = False           # usually False so JS apps can read CSRF, set True if not needed
SESSION_COOKIE_HTTPONLY = True         # prevent JS access to session cookie

# SameSite: 'Lax' is reasonable default for most sites. Use 'Strict' only if you understand implications.
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'               # or 'SAMEORIGIN' if you embed in same domain

# Basic browser protections
SECURE_BROWSER_XSS_FILTER = True       # sets X-XSS-Protection header
SECURE_CONTENT_TYPE_NOSNIFF = True    # sets X-Content-Type-Options: nosniff

# Force HTTPS and HSTS
SECURE_SSL_REDIRECT = True             # redirect all HTTP->HTTPS
SECURE_HSTS_SECONDS = 31536000         # 1 year (set lower first, then ramp up)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Optional: prevent referrer info on cross-origin requests
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'

# Add secure proxy header if behind a proxy like Nginx (set by your proxy)
# Example: 'HTTP_X_FORWARDED_PROTO' header value set to 'https' by proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

bookshelf.CustomUser"





